app/urls.py
from app.views import *
from .models_urls.bill import *
from .models_urls.client import *
from .models_urls.order import *
from .models_urls.product import *
from .models_urls.product_type import *
from .models_urls.table import *
from .models_urls.waiter import *

app_name = 'app'

urlpatterns = [
                  path('', home_view, name='index'),
              ] + waiters_urlpatterns \
              + clients_urlpatterns \
              + tables_urlpatterns \
              + p_types_urlpatterns \
              + products_urlpatterns \
              + bills_urlpatterns \
              + orders_urlpatterns

rincon_del_sabor/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt import views as jwt_views

from app import api_views

api_router = DefaultRouter()
api_router.register(r'waiters', api_views.WaiterViewSet)
api_router.register(r'clients', api_views.ClientViewSet)
api_router.register(r'tables', api_views.TableViewSet)
api_router.register(r'p_types', api_views.ProductTypeViewSet)
api_router.register(r'products', api_views.ProductViewSet)
api_router.register(r'bills', api_views.BillViewSet)
api_router.register(r'orders', api_views.OrderViewSet)

urlpatterns = [
    # app urls
    path('admin/', admin.site.urls),
    path('', include('app.urls')),

    # DRF urls
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include(api_router.urls)),

    # JWT
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
]

app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.

# Users models
class User(AbstractUser):
    pass


class Waiter(User):
    last_name2 = models.CharField(max_length=150, blank=True)

    class Meta:
        verbose_name = 'Waiter'


class Client(models.Model):
    first_name = models.CharField(max_length=150, blank=True)
    last_name = models.CharField(max_length=150, blank=True)
    observations = models.CharField(max_length=45, default='No comments')
    inactive = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        verbose_name = 'Client'


# Tables model
class Table(models.Model):
    numb_clients = models.IntegerField()
    location = models.CharField(max_length=45, null=False, blank=False)
    inactive = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.location} {self.numb_clients}'


class ProductType(models.Model):
    type = models.CharField(max_length=45, null=False, blank=False)
    detail = models.CharField(max_length=255, null=False, blank=False)
    inactive = models.BooleanField(default=False)

    def __str__(self):
        return self.type


# Products models
class Product(models.Model):
    name = models.CharField(max_length=45, null=False, blank=False)
    price = models.FloatField()
    type = models.ForeignKey(ProductType, on_delete=models.CASCADE)
    inactive = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.name}'


# Bills model
class Bill(models.Model):
    bill_date = models.DateField(auto_now_add=True, blank=False, null=False)
    client_id = models.ForeignKey(Client, on_delete=models.CASCADE)
    waiter_id = models.ForeignKey(Waiter, on_delete=models.CASCADE)
    inactive = models.BooleanField(default=False)

    def __str__(self):
        return f'Factura #{self.id}, cliente {self.client_id.full_name()}'


class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    count = models.IntegerField()
    bill_id = models.ForeignKey(Bill, on_delete=models.CASCADE, related_name='orders')
    order_date = models.DateField(auto_now_add=True, blank=False, null=False)
    table_id = models.ForeignKey(Table, on_delete=models.CASCADE)
    inactive = models.BooleanField(default=False)
    sub_total = models.FloatField(default=0)

    def __str__(self):
        return f'orden #{self.id}'

    def get_sub_total(self):
        price = self.product.price
        total = price * self.count
        return total

app/forms.py
from django import forms
from app.models import *
from django.contrib.auth.forms import UserCreationForm


# Waiter Forms
class WaiterCreateForm(UserCreationForm):
    class Meta:
        model = Waiter
        fields = ['first_name', 'last_name', 'last_name2', 'username', 'password1', 'password2',  'email']


class WaiterUpdateForm(forms.ModelForm):
    class Meta:
        model = Waiter
        fields = ['first_name', 'last_name', 'last_name2', 'email']


class WaiterDeleteForm(forms.ModelForm):
    class Meta:
        model = Waiter
        fields = ['is_active']


# Client Forms
class ClientCreateForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['first_name', 'last_name', 'observations']


class ClientUpdateForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['first_name', 'last_name', 'observations']


class ClientDeleteForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['inactive']


# Table forms
class TableCreateForm(forms.ModelForm):
    class Meta:
        model = Table
        fields = ['numb_clients', 'location']


class TableUpdateForm(forms.ModelForm):
    class Meta:
        model = Table
        fields = ['numb_clients', 'location']


class TableDeleteForm(forms.ModelForm):
    class Meta:
        model = Table
        fields = ['inactive']


# Product Type forms
class ProductTypeCreateForm(forms.ModelForm):
    class Meta:
        model = ProductType
        fields = ['type', 'detail']


class ProductTypeUpdateForm(forms.ModelForm):
    class Meta:
        model = ProductType
        fields = ['type', 'detail']


class ProductTypeDeleteForm(forms.ModelForm):
    class Meta:
        model = ProductType
        fields = ['inactive']


# Product forms
class ProductCreateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'type']


class ProductUpdateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'type']


class ProductDeleteForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['inactive']


# Bill forms
class BillCreateForm(forms.ModelForm):
    class Meta:
        model = Bill
        fields = ['client_id', 'waiter_id']


class BillUpdateForm(forms.ModelForm):
    class Meta:
        model = Bill
        fields = ['client_id', 'waiter_id']


class BillDeleteForm(forms.ModelForm):
    class Meta:
        model = Bill
        fields = ['inactive']


# Order forms
class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['product', 'count', 'bill_id', 'table_id']


class OrderUpdateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['product', 'count', 'bill_id', 'table_id']


class OrderDeleteForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['inactive']

app/views.py
from django.shortcuts import render


# Create your views here.
def home_view(request):
    return render(request, "base/index.html")

templates/app/bills/bill_detail.html
{% extends "base/base.html" %}
{% load humanize %}
{% block custom_head %}
    <style>
        body {
            margin: 0;
            padding: 0;
            font: 400 .875rem 'Open Sans', sans-serif;
            color: black;
            background: black;
            position: relative;
            height: 100%;
        }

        .invoice-container {
            padding: 1rem;
        }

        .invoice-container .invoice-header .invoice-logo {
            margin: 0.8rem 0 0 0;
            display: inline-block;
            font-size: 1.6rem;
            font-weight: 700;
            color: black;
        }

        .invoice-container .invoice-header .invoice-logo img {
            max-width: 130px;
        }

        .invoice-container .invoice-header address {
            font-size: 0.8rem;
            color: black;
            margin: 0;
        }

        .invoice-container .invoice-details {
            margin: 1rem 0 0 0;
            padding: 1rem;
            line-height: 180%;
            background: white;
        }

        .invoice-container .invoice-details .invoice-num {
            text-align: right;
            font-size: 0.8rem;
        }

        .invoice-container .invoice-body {
            padding: 1rem 0 0 0;
        }

        .invoice-container .invoice-footer {
            text-align: center;
            font-size: 0.7rem;
            margin: 5px 0 0 0;
        }

        .invoice-status {
            text-align: center;
            padding: 1rem;
            background: #272e48;
            -webkit-border-radius: 4px;
            -moz-border-radius: 4px;
            border-radius: 4px;
            margin-bottom: 1rem;
        }

        .invoice-status h2.status {
            margin: 0 0 0.8rem 0;
        }

        .invoice-status h5.status-title {
            margin: 0 0 0.8rem 0;
            color: black;
        }

        .invoice-status p.status-type {
            margin: 0.5rem 0 0 0;
            padding: 0;
            line-height: 150%;
        }

        .invoice-status i {
            font-size: 1.5rem;
            margin: 0 0 1rem 0;
            display: inline-block;
            padding: 1rem;
            background: white;
            -webkit-border-radius: 50px;
            -moz-border-radius: 50px;
            border-radius: 50px;
        }

        .invoice-status .badge {
            text-transform: uppercase;
        }

        @media (max-width: 767px) {
            .invoice-container {
                padding: 1rem;
            }
        }

        .card {
            background: white;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
            border: 0;
            margin-bottom: 1rem;
        }

        .custom-table {
            border: 1px solid black;
        }

        .custom-table thead {
            background: grey;
        }

        .custom-table thead th {
            border: 0;
            color: #ffffff;
        }


        .custom-table > tbody td {
            border: 1px solid #2e3d5f;
        }

        .table {
            background: white;
            color: black;
            font-size: .75rem;
        }

        .text-success {
            color: #c0d64a !important;
        }

        .custom-actions-btns {
            margin: auto;
            display: flex;
            justify-content: flex-end;
        }

        .custom-actions-btns .btn {
            margin: .3rem 0 .3rem .3rem;
        }

    </style>
{% endblock %}
{% block content %}
    <div class="container py-5">
        <div class="row gutters">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                <div class="card">
                    <div class="card-body p-0">
                        <div class="invoice-container">
                            <div class="invoice-header">
                                <!-- Row start -->
                                <div class="row gutters">
                                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
                                        <a href="{% url "app:index" %}" class="invoice-logo">
                                            Rincon Del Sabor
                                        </a>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        <address class="text-right">
                                            Cartagena De Indias.<br>
                                            Calle del machete, San Francisco.<br>
                                            00000 00000
                                        </address>
                                    </div>
                                </div>
                                <!-- Row end -->

                                <!-- Row start -->
                                <div class="row gutters">
                                    <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
                                        <div class="invoice-details">
                                            <address>
                                                {{ bills_details.client_id }}<br>
                                                {{ bills_details.client_id.observations }}
                                            </address>
                                        </div>
                                    </div>
                                    <div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
                                        <div class="invoice-details">
                                            <div class="invoice-num">
                                                <div>Bill - #{{ bills_details.id }}</div>
                                                <div>{{ bills_details.bill_date }}</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Row end -->

                            </div>

                            <div class="invoice-body">

                                <!-- Row start -->
                                <div class="row gutters">
                                    <div class="col-lg-12 col-md-12 col-sm-12">
                                        <div class="table-responsive">

                                                <table class="table custom-table m-0">
                                                    <thead>
                                                    <tr>
                                                        <th>Product</th>
                                                        <th>Product Type</th>
                                                        <th>Price</th>
                                                        <th>Quantity</th>
                                                        <th>Sub Total</th>
                                                    </tr>
                                                    </thead>
                                                    <tbody>

                                                    {% for order in bills_details.orders.reverse %}
                                                        <tr>
                                                            <td>
                                                                {{ order.product }}
                                                            </td>
                                                            <td>{{ order.product.type }}</td>
                                                            <td>$ {{ order.product.price | intcomma }}</td>
                                                            <td>{{ order.count }}</td>
                                                            <td>$ {{ order.get_sub_total | intcomma }}  </td>
                                                        </tr>
                                                    {% endfor %}


                                                    <thead>
                                                        <th></th>
                                                        <th></th>
                                                        <th></th>
                                                        <th>
                                                            Total
                                                        </th>
                                                        <th>$ {{ total | intcomma }}</th>
                                                    </thead>

                                                    </tbody>
                                                </table>

                                        </div>
                                    </div>
                                </div>
                                <!-- Row end -->

                            </div>

                            <div class="invoice-footer">
                                Gracias por su compra.
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/app/bills/bill_list.html
{% extends "base/datatable.html" %}
{% block title %} Listado de facturas {% endblock %}
{% block table_title %} Lista de facturas {% endblock %}
{% block table_heads %}
    <th>Cliente</th>
    <th>Mesero</th>
    <th>Fecha</th>
    <th>Acciones</th>
{% endblock %}



{% block table_body %}

    {% for bill in bills_list %}

        <tr>
            <td>{{ bill.client_id }}</td>
            <td>{{ bill.waiter_id }}</td>
            <td>{{ bill.bill_date }}</td>
            <th>
                <div class="btn-group">
                    <a href="{% url "app:bill_detail" bill.id %}" class="btn btn-success">Detalles</a>
                    <a href="{% url "app:bill_update" bill.id %}" class="btn btn-success">Editar</a>
                    <a href="{% url "app:bill_delete" bill.id %}" class="btn btn-danger">Borrar</a>
                </div>
            </th>
        </tr>

    {% endfor %}

{% endblock %}

templates/app/client/client_list.html
{% extends "base/datatable.html" %}
{% block title %} Listado de clients {% endblock %}
{% block table_title %} Lista de clientes {% endblock %}
{% block table_heads %}
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Observaciones</th>
    <th>Acciones</th>
{% endblock %}

{% block table_body %}
    {% for cliente in clients_list %}
        <tr>
            <td>{{ cliente.first_name }}</td>
            <td>{{ cliente.last_name }}</td>
            <td>{{ cliente.observations }}</td>
            <th>
                <div class="btn-group">
                    <a href="{% url "app:client_update" cliente.id %}" class="btn btn-success">Editar</a>
                    <a href="{% url "app:client_delete" cliente.id %}" class="btn btn-danger">Borrar</a>
                </div>
            </th>
        </tr>
    {% endfor %}
{% endblock %}

templates/app/order/order_list.html
{% extends "base/datatable.html" %}
{% load humanize %}
{% block title %} Listado de ordenes {% endblock %}
{% block table_title %} Lista de ordenes {% endblock %}
{% block table_heads %}
    <th>Producto</th>
    <th>Precio</th>
    <th>cantidad</th>
    <th>Total</th>
    <th>Mesa</th>
    <th>Factura asociada</th>
    <th>Fecha</th>
    <th>Acciones</th>
{% endblock %}

{% block table_body %}
    {% for order in orders_list %}
        <tr>
            <td>{{ order.product }}</td>
            <td>$ {{ order.product.price | intcomma }} COP</td>
            <td>{{ order.count }}</td>
            <td>$ {{ order.get_sub_total | intcomma }} COP</td>
            <td>{{ order.table_id }}</td>
            <td>{{ order.bill_id }}</td>
            <td>{{ order.order_date }}</td>
            <th>
                <div class="btn-group">
                    <a href="{% url "app:order_update" order.id %}" class="btn btn-success">Editar</a>
                    <a href="{% url "app:order_delete" order.id %}" class="btn btn-danger">Borrar</a>
                </div>
            </th>
        </tr>
    {% endfor %}
{% endblock %}

templates/app/product/product_list.html
{% extends "base/datatable.html" %}
{% block title %} Listado de  productos {% endblock %}
{% block table_title %} Lista de productos {% endblock %}
{% block table_heads %}
    <th>Nombre</th>
    <th>Precio</th>
    <th>Tipo</th>
    <th>Acciones</th>
{% endblock %}

{% block table_body %}
    {% for product in product_list %}
        <tr>
            <td>{{ product.name }}</td>
            <td>{{ product.price }}</td>
            <td>{{ product.type }}</td>
            <th>
                <div class="btn-group">
                    <a href="{% url "app:product_update" product.id %}" class="btn btn-success">Editar</a>
                    <a href="{% url "app:product_delete" product.id %}" class="btn btn-danger">Borrar</a>
                </div>
            </th>
        </tr>
    {% endfor %}
{% endblock %}

templates/app/product_type/product_type_list.html
{% extends "base/datatable.html" %}
{% block title %} Listado de tipos de productos {% endblock %}
{% block table_title %} Lista de tipos de productos {% endblock %}
{% block table_heads %}
    <th>Tipo</th>
    <th>Detalles</th>
    <th>Acciones</th>
{% endblock %}

{% block table_body %}
    {% for p_type in product_type_list %}
        <tr>
            <td>{{ p_type.type }}</td>
            <td>{{ p_type.detail }}</td>
            <th>
                <div class="btn-group">
                    <a href="{% url "app:p_type_update" p_type.id %}" class="btn btn-success">Editar</a>
                    <a href="{% url "app:p_type_delete" p_type.id %}" class="btn btn-danger">Borrar</a>
                </div>
            </th>
        </tr>
    {% endfor %}
{% endblock %}

templates/app/table/table_list.html
{% extends "base/datatable.html" %}
{% block title %} Listado de mesas {% endblock %}
{% block table_title %} Lista de mesas {% endblock %}
{% block table_heads %}
    <th># de mesa</th>
    <th>Ubicacion</th>
    <th>Acciones</th>
{% endblock %}

{% block table_body %}
    {% for table in table_list %}
        <tr>
            <td>{{ table.numb_clients }}</td>
            <td>{{ table.location }}</td>
            <th>
                <div class="btn-group">
                    <a href="{% url "app:table_update" table.id %}" class="btn btn-success">Editar</a>
                    <a href="{% url "app:table_delete" table.id %}" class="btn btn-danger">Borrar</a>
                </div>
            </th>
        </tr>
    {% endfor %}
{% endblock %}

templates/app/waiter/waiter_list.html
{% extends "base/datatable.html" %}
{% block title %} Listado de meseros {% endblock %}
{% block table_title %} Lista de meseros {% endblock %}
{% block table_heads %}
    <th>Nombre</th>
    <th>Primer Apellido</th>
    <th>Segundo Apellido</th>
    <th>Email</th>
    <th>Acciones</th>
{% endblock %}


{% block table_body %}
    {% for waiter in waiter_list %}
        <tr>
            <td>{{ waiter.first_name }}</td>
            <td>{{ waiter.last_name }}</td>
            <td>{{ waiter.last_name2 }}</td>
            <td>{{ waiter.email }}</td>
            <th>
                <div class="btn-group">
                    <a href="{% url "app:waiter_update" waiter.id %}" class="btn btn-success">Editar</a>
                    <a href="{% url "app:waiter_delete" waiter.id %}" class="btn btn-danger">Borrar</a>
                </div>
            </th>
        </tr>
    {% endfor %}
{% endblock %}

templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link href="{% static "assets/css/bootstrap.min.css" %}" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static "assets/css/bootstrap.css" %}"/>
    <link rel="stylesheet" href="{% static "assets/css/dataTables.bootstrap4.min.css" %}"/>


    {% block custom_head %}
        {#Custom setting in head#}
    {% endblock %}
    <style>
        body {
            background: url({% static 'assets/imgs/restaurant.jpg' %}) no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }
    </style>

    <meta charset="UTF-8">
    <title>{% block title %} Rincon del sabor {% endblock %}</title>


</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url "app:index" %}">Rincon del sabor</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="{% url "app:waiter_list" %}" id="navbarDropdownMenuLink"
                       role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Waiters
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url "app:waiter_list" %}">Listado de meseros</a></li>
                        <li><a class="dropdown-item" href="{% url "app:waiter_new" %}">Agregar mesero </a></li>
                    </ul>
                </li>
            </ul>

            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="{% url "app:client_list" %}" id="navbarDropdownMenuLink"
                       role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Clients
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url "app:client_list" %}">Listado de clientes</a></li>
                        <li><a class="dropdown-item" href="{% url "app:client_new" %}">Agregar cliente</a></li>
                    </ul>
                </li>
            </ul>

            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="{% url "app:table_list" %}" id="navbarDropdownMenuLink"
                       role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Tables
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url "app:table_list" %}">Listado de mesas</a></li>
                        <li><a class="dropdown-item" href="{% url "app:table_new" %}">Agregar mesa</a></li>
                    </ul>
                </li>
            </ul>

            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="{% url "app:p_type_list" %}" id="navbarDropdownMenuLink"
                       role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Products Types
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url "app:p_type_list" %}">Listado de T. de Productos</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url "app:p_type_new" %}">Agregar T. de Productos</a></li>
                    </ul>
                </li>
            </ul>

            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="{% url "app:product_list" %}" id="navbarDropdownMenuLink"
                       role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Products
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url "app:product_list" %}">Listado de Productos</a></li>
                        <li><a class="dropdown-item" href="{% url "app:product_new" %}">Agregar Productos</a></li>
                    </ul>
                </li>
            </ul>

            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="{% url "app:bill_list" %}" id="navbarDropdownMenuLink"
                       role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Bills
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url "app:bill_list" %}">Listado de facturas</a></li>
                        <li><a class="dropdown-item" href="{% url "app:bill_new" %}">Agregar facturas</a></li>
                    </ul>
                </li>
            </ul>

            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="{% url "app:order_list" %}" id="navbarDropdownMenuLink"
                       role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Orders
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url "app:order_list" %}">Listado de ordenes</a></li>
                        <li><a class="dropdown-item" href="{% url "app:order_new" %}">Agregar orden</a></li>
                    </ul>
                </li>
            </ul>

        </div>
    </div>
</nav>
{% block content %}
    {#Custom content#}
{% endblock %}

{% block custom_js %}
    {#Custom scripts#}
{% endblock %}


<script src="{% static "assets/js/bootstrap.bundle.js" %}"></script>
<script src="{% static "assets/js/jquery-1.12.4.js" %}"></script>
<script src="{% static "assets/js/jquery.dataTables.min.js" %}"></script>
<script src="{% static "assets/js/dataTables.bootstrap4.min.js" %}"></script>
<script>
    $(document).ready(function () {
        $('.table').DataTable({
            "pageLength": 25
        });
    });
</script>

</body>
</html>

templates/base/index.html
{% extends 'base/base.html' %}
{% block content %}
    <div class="bg-light m-5" style="border-radius: 30px">
        <h1 class="text-center text-black mx-auto p-4">
            Sitio web desarrollado para el curso de Django RestFramework - CAR IV 2022
        </h1>

        <ul class="list-group text-center p-5">
            <h2>
                <li class="">Enlaces de acciones CRUD para cada modelo en el navbar.</li>
            </h2>
            <h2>
                <li class="">Click <a href="http://localhost:8000/api/">Aqui</a> para acceder a links de la API</li>
            </h2>
        </ul>

    </div>

{% endblock %}